// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHSClub.Database;

#nullable disable

namespace SHSClub.Migrations
{
    [DbContext(typeof(SHSClubDbContext))]
    [Migration("20231128083457_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SHSClub.Models.SuperheroModel", b =>
                {
                    b.Property<int>("SuperheroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperheroId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SecretIdentity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("secret_identity");

                    b.Property<int?>("SuperpowerId")
                        .HasColumnType("int")
                        .HasColumnName("superpower_id");

                    b.HasKey("SuperheroId");

                    b.HasIndex("SuperpowerId");

                    b.ToTable("Superheroes");
                });

            modelBuilder.Entity("SHSClub.Models.SuperpowerModel", b =>
                {
                    b.Property<int>("SuperpowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperpowerId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("SuperpowerId");

                    b.ToTable("Superpowers");
                });

            modelBuilder.Entity("SHSClub.Models.SuperheroModel", b =>
                {
                    b.HasOne("SHSClub.Models.SuperpowerModel", "Superpower")
                        .WithMany("Superheroes")
                        .HasForeignKey("SuperpowerId");

                    b.Navigation("Superpower");
                });

            modelBuilder.Entity("SHSClub.Models.SuperpowerModel", b =>
                {
                    b.Navigation("Superheroes");
                });
#pragma warning restore 612, 618
        }
    }
}
